[2025-07-26T13:01:25.540+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-26T13:01:25.632+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sample_ETL.load_order_and_delivery_data manual__2025-07-26T13:01:15.635484+00:00 [queued]>
[2025-07-26T13:01:25.647+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sample_ETL.load_order_and_delivery_data manual__2025-07-26T13:01:15.635484+00:00 [queued]>
[2025-07-26T13:01:25.649+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-26T13:01:25.703+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_order_and_delivery_data> on 2025-07-26 13:01:15.635484+00:00
[2025-07-26T13:01:25.730+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=202) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-26T13:01:25.733+0000] {standard_task_runner.py:63} INFO - Started process 206 to run task
[2025-07-26T13:01:25.734+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sample_ETL', 'load_order_and_delivery_data', 'manual__2025-07-26T13:01:15.635484+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/sample_ETL.py', '--cfg-path', '/tmp/tmpbqr7t2x_']
[2025-07-26T13:01:25.738+0000] {standard_task_runner.py:91} INFO - Job 84: Subtask load_order_and_delivery_data
[2025-07-26T13:01:25.851+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-26T13:01:25.979+0000] {task_command.py:426} INFO - Running <TaskInstance: sample_ETL.load_order_and_delivery_data manual__2025-07-26T13:01:15.635484+00:00 [running]> on host 88b2e53952eb
[2025-07-26T13:01:26.368+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sample_ETL' AIRFLOW_CTX_TASK_ID='load_order_and_delivery_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-26T13:01:15.635484+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-26T13:01:15.635484+00:00'
[2025-07-26T13:01:26.370+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-26T13:01:26.390+0000] {logging_mixin.py:188} INFO - ðŸš€ Starting ETL with JSON files
[2025-07-26T13:01:26.401+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-26T13:01:26.591+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.7', 9092)]>: Broker version identified as 2.6
[2025-07-26T13:01:26.592+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-26T13:01:26.790+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-26T13:01:26.794+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-26T13:01:26.797+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Closing connection. 
[2025-07-26T13:01:27.538+0000] {cluster.py:313} WARNING - Topic orders_topic is not available during auto-create initialization
[2025-07-26T13:01:27.656+0000] {cluster.py:313} WARNING - Topic orders_topic is not available during auto-create initialization
[2025-07-26T13:01:27.768+0000] {cluster.py:313} WARNING - Topic orders_topic is not available during auto-create initialization
[2025-07-26T13:01:27.877+0000] {cluster.py:313} WARNING - Topic orders_topic is not available during auto-create initialization
[2025-07-26T13:01:27.988+0000] {cluster.py:313} WARNING - Topic orders_topic is not available during auto-create initialization
[2025-07-26T13:01:28.099+0000] {cluster.py:313} WARNING - Topic orders_topic is not available during auto-create initialization
[2025-07-26T13:01:29.917+0000] {logging_mixin.py:188} INFO - âœ… Produced 124 records to topic 'orders_topic'
[2025-07-26T13:01:29.918+0000] {logging_mixin.py:188} INFO - âœ… Orders producer completed
[2025-07-26T13:01:29.922+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-26T13:01:29.932+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.7', 9092)]>: Broker version identified as 2.6
[2025-07-26T13:01:29.933+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-26T13:01:29.936+0000] {subscription_state.py:181} INFO - Updating subscribed topics to: ('orders_topic',)
[2025-07-26T13:01:30.020+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-26T13:01:30.022+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-26T13:01:30.023+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Closing connection. 
[2025-07-26T13:01:32.161+0000] {cluster.py:401} INFO - Coordinator for group/etl_group_orders is ('coordinator-1', 'kafka', 9092, None)
[2025-07-26T13:01:32.162+0000] {base.py:788} INFO - Discovered coordinator coordinator-1 for group etl_group_orders
[2025-07-26T13:01:32.163+0000] {base.py:848} INFO - Starting new heartbeat thread
[2025-07-26T13:01:32.166+0000] {consumer.py:365} INFO - Revoking previously assigned partitions () for group etl_group_orders
[2025-07-26T13:01:32.167+0000] {base.py:419} INFO - Failed to join group etl_group_orders: NodeNotReadyError: coordinator-1
[2025-07-26T13:01:32.169+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-26T13:01:32.170+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-26T13:01:32.271+0000] {base.py:532} INFO - (Re-)joining group etl_group_orders
[2025-07-26T13:01:32.418+0000] {base.py:637} INFO - Received member id kafka-python-2.2.15-ae7f451e-54d2-4e31-a222-ce034fd88701 for group etl_group_orders; will retry join-group
[2025-07-26T13:01:32.420+0000] {base.py:419} INFO - Failed to join group etl_group_orders: [Error 79] MemberIdRequiredError
[2025-07-26T13:01:32.421+0000] {base.py:532} INFO - (Re-)joining group etl_group_orders
[2025-07-26T13:01:35.561+0000] {base.py:594} INFO - Successfully joined group etl_group_orders <Generation 1 (member_id: kafka-python-2.2.15-ae7f451e-54d2-4e31-a222-ce034fd88701, protocol: range)>
[2025-07-26T13:01:35.568+0000] {base.py:596} INFO - Elected group leader -- performing partition assignments using range
[2025-07-26T13:01:35.637+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('orders_topic', 0)]
[2025-07-26T13:01:35.638+0000] {consumer.py:249} INFO - Setting newly assigned partitions (('orders_topic', 0),) for group etl_group_orders
[2025-07-26T13:01:35.690+0000] {fetcher.py:418} INFO - Resetting offset for partition ('orders_topic', 0) to offset 0.
[2025-07-26T13:01:47.920+0000] {logging_mixin.py:188} INFO - âœ… Inserted 124 total records into orders
[2025-07-26T13:01:47.936+0000] {base.py:1052} INFO - Stopping heartbeat thread
[2025-07-26T13:01:47.938+0000] {base.py:891} INFO - Leaving consumer group (etl_group_orders).
[2025-07-26T13:01:47.960+0000] {base.py:906} INFO - LeaveGroup request for group etl_group_orders returned successfully
[2025-07-26T13:01:47.961+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Closing connection. 
[2025-07-26T13:01:47.963+0000] {fetcher.py:786} INFO - Fetch to node 1 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>
[2025-07-26T13:01:47.963+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Closing connection. 
[2025-07-26T13:01:47.965+0000] {logging_mixin.py:188} INFO - âœ… Orders consumer completed
[2025-07-26T13:01:53.010+0000] {cluster.py:313} WARNING - Topic delivery_topic is not available during auto-create initialization
[2025-07-26T13:01:53.139+0000] {logging_mixin.py:188} INFO - âœ… Produced 124 records to topic 'delivery_topic'
[2025-07-26T13:01:53.140+0000] {logging_mixin.py:188} INFO - âœ… Delivery producer completed
[2025-07-26T13:01:53.142+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-26T13:01:53.149+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.7', 9092)]>: Broker version identified as 2.6
[2025-07-26T13:01:53.150+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-26T13:01:53.152+0000] {subscription_state.py:181} INFO - Updating subscribed topics to: ('delivery_topic',)
[2025-07-26T13:01:53.215+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-26T13:01:53.217+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-26T13:01:53.217+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Closing connection. 
[2025-07-26T13:01:53.322+0000] {cluster.py:401} INFO - Coordinator for group/etl_group_delivery is ('coordinator-1', 'kafka', 9092, None)
[2025-07-26T13:01:53.323+0000] {base.py:788} INFO - Discovered coordinator coordinator-1 for group etl_group_delivery
[2025-07-26T13:01:53.325+0000] {base.py:848} INFO - Starting new heartbeat thread
[2025-07-26T13:01:53.327+0000] {consumer.py:365} INFO - Revoking previously assigned partitions () for group etl_group_delivery
[2025-07-26T13:01:53.328+0000] {base.py:419} INFO - Failed to join group etl_group_delivery: NodeNotReadyError: coordinator-1
[2025-07-26T13:01:53.331+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-26T13:01:53.332+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-26T13:01:53.434+0000] {base.py:532} INFO - (Re-)joining group etl_group_delivery
[2025-07-26T13:01:53.447+0000] {base.py:637} INFO - Received member id kafka-python-2.2.15-ac254f85-cbc9-47bc-b935-19f98d99abb8 for group etl_group_delivery; will retry join-group
[2025-07-26T13:01:53.449+0000] {base.py:419} INFO - Failed to join group etl_group_delivery: [Error 79] MemberIdRequiredError
[2025-07-26T13:01:53.453+0000] {base.py:532} INFO - (Re-)joining group etl_group_delivery
[2025-07-26T13:01:56.468+0000] {base.py:594} INFO - Successfully joined group etl_group_delivery <Generation 1 (member_id: kafka-python-2.2.15-ac254f85-cbc9-47bc-b935-19f98d99abb8, protocol: range)>
[2025-07-26T13:01:56.469+0000] {base.py:596} INFO - Elected group leader -- performing partition assignments using range
[2025-07-26T13:01:56.478+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('delivery_topic', 0)]
[2025-07-26T13:01:56.480+0000] {consumer.py:249} INFO - Setting newly assigned partitions (('delivery_topic', 0),) for group etl_group_delivery
[2025-07-26T13:01:56.485+0000] {fetcher.py:418} INFO - Resetting offset for partition ('delivery_topic', 0) to offset 0.
[2025-07-26T13:02:08.602+0000] {logging_mixin.py:188} INFO - âœ… Inserted 124 total records into delivery
[2025-07-26T13:02:08.613+0000] {base.py:1052} INFO - Stopping heartbeat thread
[2025-07-26T13:02:08.614+0000] {base.py:891} INFO - Leaving consumer group (etl_group_delivery).
[2025-07-26T13:02:08.622+0000] {base.py:906} INFO - LeaveGroup request for group etl_group_delivery returned successfully
[2025-07-26T13:02:08.623+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Closing connection. 
[2025-07-26T13:02:08.624+0000] {fetcher.py:786} INFO - Fetch to node 1 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>
[2025-07-26T13:02:08.625+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Closing connection. 
[2025-07-26T13:02:08.626+0000] {logging_mixin.py:188} INFO - âœ… Delivery consumer completed
[2025-07-26T13:02:08.627+0000] {logging_mixin.py:188} INFO - âœ… Task2 of ETL completed
[2025-07-26T13:02:08.628+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-26T13:02:08.629+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-26T13:02:08.684+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=sample_ETL, task_id=load_order_and_delivery_data, run_id=manual__2025-07-26T13:01:15.635484+00:00, execution_date=20250726T130115, start_date=20250726T130125, end_date=20250726T130208
[2025-07-26T13:02:08.758+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-26T13:02:08.830+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-26T13:02:08.851+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
