[2025-07-26T12:09:29.413+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-26T12:09:29.650+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sample_ETL.load_order_and_delivery_data manual__2025-07-26T12:09:24.145453+00:00 [queued]>
[2025-07-26T12:09:29.662+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sample_ETL.load_order_and_delivery_data manual__2025-07-26T12:09:24.145453+00:00 [queued]>
[2025-07-26T12:09:29.663+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-26T12:09:29.709+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_order_and_delivery_data> on 2025-07-26 12:09:24.145453+00:00
[2025-07-26T12:09:29.719+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=151) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-26T12:09:29.720+0000] {standard_task_runner.py:63} INFO - Started process 155 to run task
[2025-07-26T12:09:29.720+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sample_ETL', 'load_order_and_delivery_data', 'manual__2025-07-26T12:09:24.145453+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/sample_ETL.py', '--cfg-path', '/tmp/tmpgel3afgk']
[2025-07-26T12:09:29.723+0000] {standard_task_runner.py:91} INFO - Job 80: Subtask load_order_and_delivery_data
[2025-07-26T12:09:29.795+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-26T12:09:29.910+0000] {task_command.py:426} INFO - Running <TaskInstance: sample_ETL.load_order_and_delivery_data manual__2025-07-26T12:09:24.145453+00:00 [running]> on host 749540b58fec
[2025-07-26T12:09:30.176+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sample_ETL' AIRFLOW_CTX_TASK_ID='load_order_and_delivery_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-26T12:09:24.145453+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-26T12:09:24.145453+00:00'
[2025-07-26T12:09:30.178+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-26T12:09:30.195+0000] {logging_mixin.py:188} INFO - ðŸš€ Starting ETL with JSON files
[2025-07-26T12:09:30.199+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-26T12:09:30.404+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.7', 9092)]>: Broker version identified as 2.6
[2025-07-26T12:09:30.405+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-26T12:09:30.557+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-26T12:09:30.561+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-26T12:09:30.563+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Closing connection. 
[2025-07-26T12:09:31.068+0000] {cluster.py:313} WARNING - Topic orders_topic is not available during auto-create initialization
[2025-07-26T12:09:31.183+0000] {cluster.py:313} WARNING - Topic orders_topic is not available during auto-create initialization
[2025-07-26T12:09:31.294+0000] {cluster.py:313} WARNING - Topic orders_topic is not available during auto-create initialization
[2025-07-26T12:09:31.405+0000] {cluster.py:313} WARNING - Topic orders_topic is not available during auto-create initialization
[2025-07-26T12:09:31.520+0000] {cluster.py:313} WARNING - Topic orders_topic is not available during auto-create initialization
[2025-07-26T12:09:31.632+0000] {cluster.py:313} WARNING - Topic orders_topic is not available during auto-create initialization
[2025-07-26T12:09:31.909+0000] {logging_mixin.py:188} INFO - âœ… Produced 124 records to topic 'orders_topic'
[2025-07-26T12:09:31.911+0000] {logging_mixin.py:188} INFO - âœ… Orders producer completed
[2025-07-26T12:09:31.914+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-26T12:09:31.925+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.7', 9092)]>: Broker version identified as 2.6
[2025-07-26T12:09:31.926+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-26T12:09:31.929+0000] {subscription_state.py:181} INFO - Updating subscribed topics to: ('orders_topic',)
[2025-07-26T12:09:32.006+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-26T12:09:32.007+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-26T12:09:32.008+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Closing connection. 
[2025-07-26T12:09:33.855+0000] {cluster.py:401} INFO - Coordinator for group/etl_group_orders is ('coordinator-1', 'kafka', 9092, None)
[2025-07-26T12:09:33.856+0000] {base.py:788} INFO - Discovered coordinator coordinator-1 for group etl_group_orders
[2025-07-26T12:09:33.857+0000] {base.py:848} INFO - Starting new heartbeat thread
[2025-07-26T12:09:33.859+0000] {consumer.py:365} INFO - Revoking previously assigned partitions () for group etl_group_orders
[2025-07-26T12:09:33.860+0000] {base.py:419} INFO - Failed to join group etl_group_orders: NodeNotReadyError: coordinator-1
[2025-07-26T12:09:33.862+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-26T12:09:33.863+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-26T12:09:33.965+0000] {base.py:532} INFO - (Re-)joining group etl_group_orders
[2025-07-26T12:09:34.028+0000] {base.py:637} INFO - Received member id kafka-python-2.2.15-4fbcccff-485a-4300-9da9-11c4626362ad for group etl_group_orders; will retry join-group
[2025-07-26T12:09:34.029+0000] {base.py:419} INFO - Failed to join group etl_group_orders: [Error 79] MemberIdRequiredError
[2025-07-26T12:09:34.030+0000] {base.py:532} INFO - (Re-)joining group etl_group_orders
[2025-07-26T12:09:37.100+0000] {base.py:594} INFO - Successfully joined group etl_group_orders <Generation 1 (member_id: kafka-python-2.2.15-4fbcccff-485a-4300-9da9-11c4626362ad, protocol: range)>
[2025-07-26T12:09:37.102+0000] {base.py:596} INFO - Elected group leader -- performing partition assignments using range
[2025-07-26T12:09:37.146+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('orders_topic', 0)]
[2025-07-26T12:09:37.147+0000] {consumer.py:249} INFO - Setting newly assigned partitions (('orders_topic', 0),) for group etl_group_orders
[2025-07-26T12:09:37.207+0000] {fetcher.py:418} INFO - Resetting offset for partition ('orders_topic', 0) to offset 0.
[2025-07-26T12:09:49.373+0000] {logging_mixin.py:188} INFO - âœ… Inserted 124 total records into orders
[2025-07-26T12:09:49.380+0000] {base.py:1052} INFO - Stopping heartbeat thread
[2025-07-26T12:09:49.381+0000] {base.py:891} INFO - Leaving consumer group (etl_group_orders).
[2025-07-26T12:09:49.408+0000] {base.py:906} INFO - LeaveGroup request for group etl_group_orders returned successfully
[2025-07-26T12:09:49.410+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Closing connection. 
[2025-07-26T12:09:49.411+0000] {fetcher.py:786} INFO - Fetch to node 1 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>
[2025-07-26T12:09:49.418+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Closing connection. 
[2025-07-26T12:09:49.420+0000] {logging_mixin.py:188} INFO - âœ… Orders consumer completed
[2025-07-26T12:09:54.494+0000] {cluster.py:313} WARNING - Topic delivery_topic is not available during auto-create initialization
[2025-07-26T12:09:54.619+0000] {logging_mixin.py:188} INFO - âœ… Produced 124 records to topic 'delivery_topic'
[2025-07-26T12:09:54.620+0000] {logging_mixin.py:188} INFO - âœ… Delivery producer completed
[2025-07-26T12:09:54.622+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-26T12:09:54.629+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.7', 9092)]>: Broker version identified as 2.6
[2025-07-26T12:09:54.630+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-26T12:09:54.631+0000] {subscription_state.py:181} INFO - Updating subscribed topics to: ('delivery_topic',)
[2025-07-26T12:09:54.674+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-26T12:09:54.675+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-26T12:09:54.676+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Closing connection. 
[2025-07-26T12:09:54.781+0000] {cluster.py:401} INFO - Coordinator for group/etl_group_delivery is ('coordinator-1', 'kafka', 9092, None)
[2025-07-26T12:09:54.783+0000] {base.py:788} INFO - Discovered coordinator coordinator-1 for group etl_group_delivery
[2025-07-26T12:09:54.784+0000] {base.py:848} INFO - Starting new heartbeat thread
[2025-07-26T12:09:54.786+0000] {consumer.py:365} INFO - Revoking previously assigned partitions () for group etl_group_delivery
[2025-07-26T12:09:54.786+0000] {base.py:419} INFO - Failed to join group etl_group_delivery: NodeNotReadyError: coordinator-1
[2025-07-26T12:09:54.789+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-26T12:09:54.790+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-26T12:09:54.892+0000] {base.py:532} INFO - (Re-)joining group etl_group_delivery
[2025-07-26T12:09:54.897+0000] {base.py:637} INFO - Received member id kafka-python-2.2.15-10b40322-a6ba-41ff-b27f-9bfa2d2606a7 for group etl_group_delivery; will retry join-group
[2025-07-26T12:09:54.899+0000] {base.py:419} INFO - Failed to join group etl_group_delivery: [Error 79] MemberIdRequiredError
[2025-07-26T12:09:54.901+0000] {base.py:532} INFO - (Re-)joining group etl_group_delivery
[2025-07-26T12:09:57.912+0000] {base.py:594} INFO - Successfully joined group etl_group_delivery <Generation 1 (member_id: kafka-python-2.2.15-10b40322-a6ba-41ff-b27f-9bfa2d2606a7, protocol: range)>
[2025-07-26T12:09:57.913+0000] {base.py:596} INFO - Elected group leader -- performing partition assignments using range
[2025-07-26T12:09:57.920+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('delivery_topic', 0)]
[2025-07-26T12:09:57.921+0000] {consumer.py:249} INFO - Setting newly assigned partitions (('delivery_topic', 0),) for group etl_group_delivery
[2025-07-26T12:09:57.926+0000] {fetcher.py:418} INFO - Resetting offset for partition ('delivery_topic', 0) to offset 0.
[2025-07-26T12:10:10.021+0000] {logging_mixin.py:188} INFO - âœ… Inserted 124 total records into delivery
[2025-07-26T12:10:10.042+0000] {base.py:1052} INFO - Stopping heartbeat thread
[2025-07-26T12:10:10.046+0000] {base.py:891} INFO - Leaving consumer group (etl_group_delivery).
[2025-07-26T12:10:10.068+0000] {base.py:906} INFO - LeaveGroup request for group etl_group_delivery returned successfully
[2025-07-26T12:10:10.071+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Closing connection. 
[2025-07-26T12:10:10.073+0000] {fetcher.py:786} INFO - Fetch to node 1 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>
[2025-07-26T12:10:10.076+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Closing connection. 
[2025-07-26T12:10:10.080+0000] {logging_mixin.py:188} INFO - âœ… Delivery consumer completed
[2025-07-26T12:10:10.082+0000] {logging_mixin.py:188} INFO - âœ… Task2 of ETL completed
[2025-07-26T12:10:10.085+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-26T12:10:10.090+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-26T12:10:10.225+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=sample_ETL, task_id=load_order_and_delivery_data, run_id=manual__2025-07-26T12:09:24.145453+00:00, execution_date=20250726T120924, start_date=20250726T120929, end_date=20250726T121010
[2025-07-26T12:10:10.271+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-26T12:10:10.335+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-26T12:10:10.355+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
