[2025-07-26T08:47:37.370+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-26T08:47:37.442+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sample_ETL.load_order_and_delivery_data manual__2025-07-26T08:47:27.192044+00:00 [queued]>
[2025-07-26T08:47:37.454+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sample_ETL.load_order_and_delivery_data manual__2025-07-26T08:47:27.192044+00:00 [queued]>
[2025-07-26T08:47:37.455+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-26T08:47:37.496+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_order_and_delivery_data> on 2025-07-26 08:47:27.192044+00:00
[2025-07-26T08:47:37.505+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=100) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-26T08:47:37.507+0000] {standard_task_runner.py:63} INFO - Started process 101 to run task
[2025-07-26T08:47:37.505+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sample_ETL', 'load_order_and_delivery_data', 'manual__2025-07-26T08:47:27.192044+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/sample_ETL.py', '--cfg-path', '/tmp/tmpg_semgc9']
[2025-07-26T08:47:37.508+0000] {standard_task_runner.py:91} INFO - Job 73: Subtask load_order_and_delivery_data
[2025-07-26T08:47:37.608+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-26T08:47:37.731+0000] {task_command.py:426} INFO - Running <TaskInstance: sample_ETL.load_order_and_delivery_data manual__2025-07-26T08:47:27.192044+00:00 [running]> on host 6661e8fc1e4f
[2025-07-26T08:47:38.132+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sample_ETL' AIRFLOW_CTX_TASK_ID='load_order_and_delivery_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-26T08:47:27.192044+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-26T08:47:27.192044+00:00'
[2025-07-26T08:47:38.139+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-26T08:47:38.164+0000] {logging_mixin.py:188} INFO - ðŸš€ Starting ETL with JSON files
[2025-07-26T08:47:38.178+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-26T08:47:38.356+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.7', 9092)]>: Broker version identified as 2.6
[2025-07-26T08:47:38.357+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-26T08:47:38.504+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-26T08:47:38.506+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-26T08:47:38.507+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Closing connection. 
[2025-07-26T08:47:38.732+0000] {cluster.py:313} WARNING - Topic orders_topic is not available during auto-create initialization
[2025-07-26T08:47:38.843+0000] {cluster.py:313} WARNING - Topic orders_topic is not available during auto-create initialization
[2025-07-26T08:47:38.953+0000] {cluster.py:313} WARNING - Topic orders_topic is not available during auto-create initialization
[2025-07-26T08:47:39.061+0000] {cluster.py:313} WARNING - Topic orders_topic is not available during auto-create initialization
[2025-07-26T08:47:39.273+0000] {logging_mixin.py:188} INFO - âœ… Produced 124 records to topic 'orders_topic'
[2025-07-26T08:47:39.274+0000] {logging_mixin.py:188} INFO - âœ… Orders producer completed
[2025-07-26T08:47:39.276+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-26T08:47:39.283+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.7', 9092)]>: Broker version identified as 2.6
[2025-07-26T08:47:39.284+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-26T08:47:39.285+0000] {subscription_state.py:181} INFO - Updating subscribed topics to: ('orders_topic',)
[2025-07-26T08:47:39.349+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-26T08:47:39.350+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-26T08:47:39.351+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Closing connection. 
[2025-07-26T08:47:41.628+0000] {cluster.py:401} INFO - Coordinator for group/etl_group_orders is ('coordinator-1', 'kafka', 9092, None)
[2025-07-26T08:47:41.629+0000] {base.py:788} INFO - Discovered coordinator coordinator-1 for group etl_group_orders
[2025-07-26T08:47:41.630+0000] {base.py:848} INFO - Starting new heartbeat thread
[2025-07-26T08:47:41.632+0000] {consumer.py:365} INFO - Revoking previously assigned partitions () for group etl_group_orders
[2025-07-26T08:47:41.632+0000] {base.py:419} INFO - Failed to join group etl_group_orders: NodeNotReadyError: coordinator-1
[2025-07-26T08:47:41.634+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-26T08:47:41.635+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-26T08:47:41.736+0000] {base.py:532} INFO - (Re-)joining group etl_group_orders
[2025-07-26T08:47:41.764+0000] {base.py:637} INFO - Received member id kafka-python-2.2.15-805979dd-4cfd-4f69-9dc0-846fb0c72a76 for group etl_group_orders; will retry join-group
[2025-07-26T08:47:41.765+0000] {base.py:419} INFO - Failed to join group etl_group_orders: [Error 79] MemberIdRequiredError
[2025-07-26T08:47:41.766+0000] {base.py:532} INFO - (Re-)joining group etl_group_orders
[2025-07-26T08:47:44.804+0000] {base.py:594} INFO - Successfully joined group etl_group_orders <Generation 1 (member_id: kafka-python-2.2.15-805979dd-4cfd-4f69-9dc0-846fb0c72a76, protocol: range)>
[2025-07-26T08:47:44.805+0000] {base.py:596} INFO - Elected group leader -- performing partition assignments using range
[2025-07-26T08:47:44.840+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('orders_topic', 0)]
[2025-07-26T08:47:44.841+0000] {consumer.py:249} INFO - Setting newly assigned partitions (('orders_topic', 0),) for group etl_group_orders
[2025-07-26T08:47:44.873+0000] {fetcher.py:418} INFO - Resetting offset for partition ('orders_topic', 0) to offset 0.
[2025-07-26T08:47:57.069+0000] {logging_mixin.py:188} INFO - âœ… Inserted 124 total records into orders
[2025-07-26T08:47:57.089+0000] {base.py:1052} INFO - Stopping heartbeat thread
[2025-07-26T08:47:57.091+0000] {base.py:891} INFO - Leaving consumer group (etl_group_orders).
[2025-07-26T08:47:57.116+0000] {base.py:906} INFO - LeaveGroup request for group etl_group_orders returned successfully
[2025-07-26T08:47:57.118+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Closing connection. 
[2025-07-26T08:47:57.119+0000] {fetcher.py:786} INFO - Fetch to node 1 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>
[2025-07-26T08:47:57.120+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Closing connection. 
[2025-07-26T08:47:57.122+0000] {logging_mixin.py:188} INFO - âœ… Orders consumer completed
[2025-07-26T08:48:02.158+0000] {cluster.py:313} WARNING - Topic delivery_topic is not available during auto-create initialization
[2025-07-26T08:48:02.283+0000] {logging_mixin.py:188} INFO - âœ… Produced 124 records to topic 'delivery_topic'
[2025-07-26T08:48:02.284+0000] {logging_mixin.py:188} INFO - âœ… Delivery producer completed
[2025-07-26T08:48:02.286+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-26T08:48:02.293+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.7', 9092)]>: Broker version identified as 2.6
[2025-07-26T08:48:02.294+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-26T08:48:02.295+0000] {subscription_state.py:181} INFO - Updating subscribed topics to: ('delivery_topic',)
[2025-07-26T08:48:02.349+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-26T08:48:02.350+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-26T08:48:02.351+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Closing connection. 
[2025-07-26T08:48:02.454+0000] {cluster.py:401} INFO - Coordinator for group/etl_group_delivery is ('coordinator-1', 'kafka', 9092, None)
[2025-07-26T08:48:02.455+0000] {base.py:788} INFO - Discovered coordinator coordinator-1 for group etl_group_delivery
[2025-07-26T08:48:02.456+0000] {base.py:848} INFO - Starting new heartbeat thread
[2025-07-26T08:48:02.457+0000] {consumer.py:365} INFO - Revoking previously assigned partitions () for group etl_group_delivery
[2025-07-26T08:48:02.458+0000] {base.py:419} INFO - Failed to join group etl_group_delivery: NodeNotReadyError: coordinator-1
[2025-07-26T08:48:02.460+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.7', 9092)]>: connecting to kafka:9092 [('172.18.0.7', 9092) IPv4]
[2025-07-26T08:48:02.461+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Connection complete.
[2025-07-26T08:48:02.562+0000] {base.py:532} INFO - (Re-)joining group etl_group_delivery
[2025-07-26T08:48:02.566+0000] {base.py:637} INFO - Received member id kafka-python-2.2.15-f9c5a8f4-2ed2-4759-ac45-06689b7357de for group etl_group_delivery; will retry join-group
[2025-07-26T08:48:02.567+0000] {base.py:419} INFO - Failed to join group etl_group_delivery: [Error 79] MemberIdRequiredError
[2025-07-26T08:48:02.567+0000] {base.py:532} INFO - (Re-)joining group etl_group_delivery
[2025-07-26T08:48:05.572+0000] {base.py:594} INFO - Successfully joined group etl_group_delivery <Generation 1 (member_id: kafka-python-2.2.15-f9c5a8f4-2ed2-4759-ac45-06689b7357de, protocol: range)>
[2025-07-26T08:48:05.573+0000] {base.py:596} INFO - Elected group leader -- performing partition assignments using range
[2025-07-26T08:48:05.580+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('delivery_topic', 0)]
[2025-07-26T08:48:05.581+0000] {consumer.py:249} INFO - Setting newly assigned partitions (('delivery_topic', 0),) for group etl_group_delivery
[2025-07-26T08:48:05.585+0000] {fetcher.py:418} INFO - Resetting offset for partition ('delivery_topic', 0) to offset 0.
[2025-07-26T08:48:17.705+0000] {logging_mixin.py:188} INFO - âœ… Inserted 124 total records into delivery
[2025-07-26T08:48:17.713+0000] {base.py:1052} INFO - Stopping heartbeat thread
[2025-07-26T08:48:17.714+0000] {base.py:891} INFO - Leaving consumer group (etl_group_delivery).
[2025-07-26T08:48:17.718+0000] {base.py:906} INFO - LeaveGroup request for group etl_group_delivery returned successfully
[2025-07-26T08:48:17.719+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Closing connection. 
[2025-07-26T08:48:17.720+0000] {fetcher.py:786} INFO - Fetch to node 1 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>
[2025-07-26T08:48:17.721+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=kafka:9092 <connected> [IPv4 ('172.18.0.7', 9092)]>: Closing connection. 
[2025-07-26T08:48:17.721+0000] {logging_mixin.py:188} INFO - âœ… Delivery consumer completed
[2025-07-26T08:48:17.722+0000] {logging_mixin.py:188} INFO - âœ… Task2 of ETL completed
[2025-07-26T08:48:17.723+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-26T08:48:17.724+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-26T08:48:17.771+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=sample_ETL, task_id=load_order_and_delivery_data, run_id=manual__2025-07-26T08:47:27.192044+00:00, execution_date=20250726T084727, start_date=20250726T084737, end_date=20250726T084817
[2025-07-26T08:48:17.810+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-26T08:48:17.870+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-26T08:48:17.886+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
